// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqoweezgwzzjysgpgtth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxb3dlZXpnd3p6anlzZ3BndHRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDg2NTIsImV4cCI6MjA2NTU4NDY1Mn0.m5xlULvUZ28HiPovWL_reA0bEQ0ui3FwL4j2YfO-YYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);